#!/usr/bin/env bash
set -euo pipefail

# extract_functions_llvmcov.sh — list libmcs functions via llvm-cov report.
#
# Compiles libmcs into a static archive with LLVM coverage instrumentation,
# links it against an empty main, then uses `llvm-cov report -empty-profile`
# to get every function the coverage mapping knows about (no execution needed).
#
# Output: <output_file> with one function name per line, plus the raw
# llvm-cov report saved next to it as <output_file>.report.
#
# Complements extract_functions.sh (which uses nm). This script is the
# llvm-cov-canonical view: it includes every function with a coverage
# mapping, including ones nm wouldn't list.
#
# Usage: extract_functions_llvmcov.sh <output_file>

OUTPUT="${1:?Usage: extract_functions_llvmcov.sh <output_file>}"

LIBMCS="${LIBMCS:-/home/leochanj/Desktop/libmcs/libm}"
C_SRC_DIRS="${C_SRC_DIRS:-${LIBMCS}/mathd ${LIBMCS}/mathf ${LIBMCS}/common ${LIBMCS}/complexd ${LIBMCS}/complexf}"
C_INCLUDE_DIRS="${C_INCLUDE_DIRS:-${LIBMCS}/include}"
CC="${CC:-clang-21}"
LLVM_COV="${LLVM_COV:-llvm-cov-21}"
AR="${AR:-ar}"

# Doc-only files with no compiled code
EXCLUDE_FILES="cmplx.c|isfinite.c|isgreater.c|isgreaterequal.c|isinf.c|isless.c|islessequal.c|islessgreater.c|isnan.c|isnormal.c|isunordered.c|fenv.c"

echo "Building libmcs.a with LLVM coverage instrumentation..."

BDIR=$(mktemp -d)
trap 'rm -rf "$BDIR"' EXIT

INC_FLAGS=""
for d in $C_INCLUDE_DIRS; do INC_FLAGS="$INC_FLAGS -I$d"; done

COV_FLAGS="-fprofile-instr-generate -fcoverage-mapping -O0 -fno-builtin"

# ── Step 1: compile every library .c with coverage ──
for d in $C_SRC_DIRS; do
    [ -d "$d" ] || continue
    find "$d" -name '*.c' -type f | grep -vE "$EXCLUDE_FILES" | while read -r cfile; do
        oname="${BDIR}/$(basename "$(dirname "$cfile")")_$(basename "$cfile" .c).o"
        $CC $INC_FLAGS $COV_FLAGS -c "$cfile" -o "$oname" 2>/dev/null || true
    done
done

OBJS=$(find "$BDIR" -name '*.o' -type f | sort)
[ -n "$OBJS" ] || { echo "Error: no object files compiled" >&2; exit 1; }

# ── Step 2: archive into libmcs.a ──
$AR rcs "${BDIR}/libmcs.a" $OBJS

# ── Step 3: empty main, linked against the archive ──
cat > "${BDIR}/empty_main.c" << 'EOF'
int main(void) { return 0; }
EOF

# Link the whole archive so every function is pulled in (otherwise the
# linker would drop unreferenced symbols and we'd lose coverage entries).
$CC $INC_FLAGS $COV_FLAGS "${BDIR}/empty_main.c" \
    -Wl,--whole-archive "${BDIR}/libmcs.a" -Wl,--no-whole-archive \
    -lm -Wl,--allow-multiple-definition \
    -o "${BDIR}/empty_bin" 2>/dev/null || {
    echo "Error: link failed" >&2
    exit 1
}

# ── Step 4: llvm-cov report -empty-profile (no execution) ──
RAW_REPORT="${BDIR}/report.txt"
$LLVM_COV report "${BDIR}/empty_bin" -empty-profile \
    -show-functions \
    $(find $C_SRC_DIRS -name '*.c' -type f | grep -vE "$EXCLUDE_FILES") \
    > "$RAW_REPORT" 2>/dev/null || {
    # Fall back to file-level report if -show-functions form fails
    $LLVM_COV report "${BDIR}/empty_bin" -empty-profile > "$RAW_REPORT" 2>/dev/null || true
}

# ── Step 5: parse function names from the report ──
# `llvm-cov report -show-functions` lines look like:
#   <funcname>   <regions> <miss> ... <line cov>
# The "TOTAL" / "Files which contain no functions" / header lines are skipped.
{
    echo "# libmcs functions (via llvm-cov report -empty-profile)"
    echo "# Generated by: extract_functions_llvmcov.sh"
    echo "# Compiler: ${CC}, Coverage tool: ${LLVM_COV}"
    echo ""
    awk '
    /^-+$/ { next }
    /^Filename/ { next }
    /^TOTAL/ { next }
    /^Files which/ { next }
    NF >= 4 && $1 !~ /\.c$/ && $1 !~ /^\// {
        print $1
    }
    ' "$RAW_REPORT" | sort -u
} > "$OUTPUT"

# Also keep the raw report next to the output for inspection
cp "$RAW_REPORT" "${OUTPUT}.report"

_count=$(grep -c -v '^#\|^$' "$OUTPUT" || echo 0)
echo "  ${_count} functions -> ${OUTPUT}"
echo "  Raw report -> ${OUTPUT}.report"
